### ISSUE TITLE
Message.OnCreateBufferedCopy is causing unusually high memory allocations.

### ISSUE THREAD

**Issue by ganarrg999** [DigDes/SoapCore#1084]
We are seeing this in Appinsights performance improvement suggestions.

7% of your Memory was spent in Message.OnCreateBufferedCopy called from SoapCore.HeadersHelper.GetSoapAction. We expected this value to be <3%. Consider investigating why Message.OnCreateBufferedCopy is causing higher than expected memory allocations.

Can someone please throw some light on this ?

**Comment by andersjonsson** [comment]
Because a Message body can only be read once CreateBufferedCopy is used to parse the soap action in GetSoapAction.
https://github.com/DigDes/SoapCore/blob/6f49042678cbcdcde196bcabf536281d4de3b625/src/SoapCore/HeadersHelper.cs#L19-L26

That code could probably be moved down here, so that the copy is created only when the action-header is missing.
https://github.com/DigDes/SoapCore/blob/6f49042678cbcdcde196bcabf536281d4de3b625/src/SoapCore/HeadersHelper.cs#L125-L128 

Feel like testing that theory, as you seem to have good baseline to test against now? If you do, and it works out, please submit a PR.




In the long run I believe the best thing would be to move away from the Message class as there is code tied to the Message class that can't be made async today, hindering performance work there.

Unfortunately that is an investment that I don't have the time for (but I would gladly review a PR for it ;)

**Comment by ganarrg999** [comment]
I will try to change and create a PR. A few questions.
  i) Is there a documentation to clone the project and setup in local.
 ii) Is there a plan to publish .net8 target framework anytime soon?

Sorry, I am a newbie to C#, .Net world.

**Comment by andersjonsson** [comment]
> Is there a documentation to clone the project and setup in local. 

Sorry, no. Fortunately it's a straight forward project. If you clone it you should be able to build the source and run all unit tests without additional setup.

> Is there a plan to publish .net8 target framework anytime soon?

You can use SoapCore from .net8 now without issues but yes, the target framework should be updated. Work has been started but I haven't had the time to finish. Hopefully before the end of the year. I'm planning to remove a lot of obsolete stuff at the same time
