### ISSUE TITLE
SoapCore can't parse complex object in request from SoapUI that has been generated from the SoapCore WSDL

### ISSUE THREAD

**Issue by dhilgarth** [DigDes/SoapCore#131]
I have used the SoapCore sample server from this repository and started it.
I then imported the WSDL - for DataContractSerializer and XmlSerializer - into SoapUI and made calls into the service using the requests that SoapUI generated from the WSDL.

The calls were successful - no exceptions - but the server received an empty complex object, without the data that I actually sent. For XmlSerializer, some properties were set, like the string property, for DataContractSerializer, none were set.

Is this a know problem? A regression? Or was this never tested?

**Comment by andradf** [comment]
Same issue with proxies generated via svcutil. It seems to be an issue with the generated WSDL. Comparing a WCF hosted service with it's SoapCore counterpart, the only major difference in the generated schema seems to be that WCF puts thecomplex models in a separate <xs:schema> with targetNamespace http://schemas.datacontract.org/2004/07/ModelNamespace" and SoapCore places them in the same namespace as the actions. Also, the WCF schema has an extra <xs:schema> with target namespace http://schemas.microsoft.com/2003/10/Serialization/ that seems to define all the primitive .net types.

**Comment by ColoradoOrion** [comment]
I wanted to capture some thoughts. Not entirely sure it's related. I can look more later....

I found that I got a wsdl back but the Sample's console reported exceptions when generating the list of ComplexObject. Digging further, writing out `List<ComplexObject> ComplexListProperty` throws an exception. This happens because MetaWCFBodyWriter seems to assume that the type the IEnumerable (List) contains will be a basic type but it's a "complex type".

`ResolveSystemtype()` is called from 4 places. I think in this case, you'd want to return a name of null, have the expression on line 630 eval to false, drop down and add the List to the queue of complex objects. I can't speak for the other cases yet.
