### ISSUE TITLE
Allow body response element naming

### ISSUE THREAD

**Issue by ms007** [DigDes/SoapCore#137]
For serialization with the XMLSerializer, you cannot choose the name of the response element yourself. It is always set to the name of the object type. 

In the class [ServiceBodyWriter](https://github.com/DigDes/SoapCore/blob/3f3fdb4f44e0b21f549afc7c71c1f82251306eb8/src/SoapCore/ServiceBodyWriter.cs#L125) the name of the parameter is set depending on the variable needResponseEnvelope beeing set to true. 

My Service response body part has to look like this: (with correct getArtifactIDResult casing)
```
<s:Body>
  <getArtifactIDResult xmlns="http://xmlns.xxx.xx/yy/artifact">
    <return>
      <id>xxyyzz</id>
    </return>
  </getArtifactIDResult>
</s:Body>
```

But the class name of the message is GetArtifactIdResult. I have no option to set the name used for the serialization via attributes. 

If I change the line to `CachedXmlSerializer.GetXmlSerializer(resultType,  _resultName, _serviceNamespace);` it works for me, but I don't really want to fork.

How can I contribute?

**Comment by kotovaleksandr** [comment]
Please, send PR

**Comment by DeathOfLuggage** [comment]
I have a similar issue but I disagree with the change that is proposed here. 
I also need to influence the element name of the result but on top of that, I also need to change the namespace of the result. The proper solution would be to support the XmlRootAttribute on the class of the return type. As it is now, this is ignored.

By adding support it would solve both ms007's problem as well as mine. I'm looking into how to implement this change but due to time restrictions I fear I won't get to this soon.

In the example of ms007, the attribute would be like below where, in my case, there would be a different namespace aswell. 
My first instinct is to say that the call to "CachedXmlSerializer.GetXmlSerializer" should then use the information from the "XmlRootAttribute", if present, and otherwise revert back to the current behavior.

```
[XmlRoot(ElementName = "getArtifactIDResult", Namespace = "http://xmlns.xxx.xx/yy/artifact")]
public class GetArtifactIDResult
{
}

```

**Comment by kotovaleksandr** [comment]
@DeathOfLuggage thanks for explaining!
@ms007 Can you provide minimal example for reproduce your issue? I can to try fix your problem by @DeathOfLuggage solution with XmlRootAttribute.

**Comment by DeathOfLuggage** [comment]
@kotovaleksandr 
I made a quick fix for the issue (on my end) but am not able to make the testcases for an official PR. Just so you have it, here is my fix. If time allows, I'll look into a testcase so that I can do an official PR, but for now I don't have the time.

@ms007 If you have the minimal example I could check if the solution for my problem also covers yours

This bit should replace [line 125 of the ServiceBodyWriter](https://github.com/DigDes/SoapCore/blob/master/src/SoapCore/ServiceBodyWriter.cs#L125).

```
// Quick check for XmlRootAttribute, maybe this should be done inside the OperationDescription class?
var xmlRootAttr = resultType.GetTypeInfo().GetCustomAttributes<XmlRootAttribute>().FirstOrDefault();
var xmlName = string.IsNullOrWhiteSpace(xmlRootAttr?.ElementName) ? resultType.Name : xmlRootAttr.ElementName;
var xmlNs = string.IsNullOrWhiteSpace(xmlRootAttr?.Namespace) ? _serviceNamespace : xmlRootAttr.Namespace;

var serializer = CachedXmlSerializer.GetXmlSerializer(resultType, needResponseEnvelope ? _resultName : xmlName, xmlNs);
```

**Comment by ms007** [comment]
@DeathOfLuggage I have tried your solution in my current fork and it solves the problem perfectly.

I like that

**Comment by ms007** [comment]
@DeathOfLuggage @kotovaleksandr 
Please find the minimal example here: https://github.com/ms007/SoapCoreTest

The solution comes with the current SoapCore project and the suggested fix.
But the root element with the custom name is commented out: [here](https://github.com/ms007/SoapCoreTest/blob/c6fbe70b49781f05b6e3dc864eb68f9020be6b03/ArtefactService/Messages/GetArtifactIdResponse.cs#L8)

**Comment by ms007** [comment]
Thank you for merging this PR. Do you have plans for shipping a new NuGet?

**Comment by kotovaleksandr** [comment]
@ms007 next week

**Comment by kotovaleksandr** [comment]
https://www.nuget.org/packages/SoapCore/0.9.9
