### ISSUE TITLE
After upgrading to 0.9.9.5 I get an error

### ISSUE THREAD

**Issue by MCFHTAGENTS** [DigDes/SoapCore#248]
I am seeing an error as follows in the logs:

 `Index was outside the bounds of the array.`

The code is somewhere between my code and my calling progam code but I can't show a stack trace and you seem to have limited tracing.

Reverting back to 0.9.9.2 it doesn't happen.

Can we easily see the code changes between releases? 

Thanks
Mark

**Comment by MCFHTAGENTS** [comment]
Can refine this as a breaking change between 0.9.9.4 and 0.9.9.5

**Comment by kotovaleksandr** [comment]
Hi @MCFHTAGENTS Please provide more details about your error. Between 9.4 and 9.5 version there were a lot of changes, it's hard to determine exactly what caused the error

**Comment by MCFHTAGENTS** [comment]
Any thoughts on how I can do that :)  - I am running verbose logging across my MVC Core app and not seeing any logging from your code. The calling application is a third party product (QuickBooks Web Connector) so I can't run it in a debug mode. The logging it creates 
```
20190426.16:20:28 UTC	: QBWebConnector.SOAPWebService.do_authenticate() : *** Calling authenticate() with following parameters:<MaskedForSecurity>
20190426.16:20:29 UTC	: QBWebConnector.SOAPWebService.do_authenticate() : QBWC1012: Authentication failed due to following error message.
Index was outside the bounds of the array.
More info:
StackTrace =    at QBWebConnector.WebService.do_authenticate(String& ticket, String& companyFileName)
Source = QBWebConnector
```
I assume **do_authenticate** is inside the QuickBooks binary. and that the exception is coming either from inside your code, or you are not returning an array of 4 strings (which is what I am passing back from my method) and therefore the quickbooks application itself is throwing an exception which it then catches.
 
Server side I see an entry in the log where my controller method completes but no further entries are recorded.

If it helps my method returns a string array under all scenarios.

The authenticate method in question is decorated with 
```
[OperationContract(Action= "http://developer.intuit.com/authenticate")]
string[] authenticate(string strUserName, string strPassword);
```
and the controller with
```
[ServiceContract(Namespace = "http://developer.intuit.com/", SessionMode = SessionMode.Required)]
```

Thanks
Mark

**Comment by kotovaleksandr** [comment]
Maybe try catch exception with debugger? And maybe latest version of soapcore don’t throw any exceptions, but return empty string collection?

Sent from my iPhone

On 26 Apr 2019, at 19:33, MCFHTAGENTS <notifications@github.com<mailto:notifications@github.com>> wrote:


Any thoughts on how I can do that :) - I am running verbose logging across my MVC Core app and not seeing any logging from your code. The calling application is a third party product (QuickBooks Web Connector) so I can't run it in a debug mode. The logging it creates

20190426.16:20:28 UTC   : QBWebConnector.SOAPWebService.do_authenticate() : *** Calling authenticate() with following parameters:<MaskedForSecurity>
20190426.16:20:29 UTC   : QBWebConnector.SOAPWebService.do_authenticate() : QBWC1012: Authentication failed due to following error message.
Index was outside the bounds of the array.
More info:
StackTrace =    at QBWebConnector.WebService.do_authenticate(String& ticket, String& companyFileName)
Source = QBWebConnector


I assume do_authenticate is inside the QuickBooks binary. and that the exception is coming either from inside your code, or you are not returning an array of 4 strings (which is what I am passing back from my method) and therefore the quickbooks application itself is throwing an exception which it then catches.

Server side I see an entry in the log where my controller method completes but no further entries are recorded.

If it helps my method returns a string array under all scenarios.

The authenticate method in question is decorated with

[OperationContract(Action= "http://developer.intuit.com/authenticate")]
string[] authenticate(string strUserName, string strPassword);


and the controller with

[ServiceContract(Namespace = "http://developer.intuit.com/", SessionMode = SessionMode.Required)]


Thanks
Mark

**Comment by MCFHTAGENTS** [comment]
OK - I didn't realise MS now allowed remote debugging with the VS 2019 community edition :)

I have run both ends in a debugger with all managed code exceptions set to break on when they are thrown and am see no exceptions thrown that I can catch in a debugger (remember my client will be release code so may not expose them) so I think your hypothesis 

>  maybe latest version of soapcore don’t throw any exceptions, but return empty string collection?

sounds promising
Thanks
Mark

**Comment by MCFHTAGENTS** [comment]
OK - I built a stub client and can confirm that an empty string array is being passed back from your code when I pass in an array with 4 values.

**Comment by kotovaleksandr** [comment]
Please give example of service and Startup.cs class, i can't reproduce on my project.

**Comment by MCFHTAGENTS** [comment]
Ok thank you - give me a few days and will revert

**Comment by MCFHTAGENTS** [comment]
This should show all the relevant code. I have also now fully confirmed under the old code base  I get an array of 4 strings (one of which is null by design) with my code.


**Startup.cs:**
`            app.UseSoapEndpoint<Controllers.IQuickBooksService>( "/QBIntegration.asmx", new BasicHttpBinding(BasicHttpSecurityMode.Transport), SoapSerializer.XmlSerializer);
`

**Controller class:**
```
    [ServiceContract(Namespace = "http://developer.intuit.com/", SessionMode = SessionMode.Required)]
    public interface IQuickBooksService
    {
        [OperationContract(Action= "http://developer.intuit.com/authenticate")]
        string[] authenticate(string strUserName, string strPassword);
     }

    public class QuickBooksController : IQuickBooksService
    {
        public QuickBooksController(
            )
        {
        }


        public string[] authenticate(string strUserName, string strPassword)
        {
            _logger.LogDebug("Calling authenticate({0}, ***Masked***)", strUserName);
            Guid UserID;
            string[] authReturn = new string[4];
            authReturn[0] = "";
            authReturn[1] = "nvu";
            authReturn[2] = null;
            authReturn[3] = "600";
            return authReturn;
        }
    }
```
Test Harness:
```
        static void Main(string[] args)
        {
            ServicePointManager.ServerCertificateValidationCallback +=
        (sender, cert, chain, error) =>
        {
            return true;
        }; ;
            IQuickBooksService Service = new IQuickBooksService();
            string[] TestMe = Service.authenticate("mcfh@outlook.com", "10Eccleston!");
            int iItem = 0;
            foreach(var Item in TestMe)
            {
                iItem++;
                Console.WriteLine("{0}: {1}", iItem, TestMe[iItem] );
            }
        }
    }
```

Thanks for your help

Mark
