### ISSUE TITLE
Input parameter validation

### ISSUE THREAD

**Issue by YaroslavKormushyn** [DigDes/SoapCore#442]
Does SoapCore provide a way for validating operation contract input parameters?
Or maybe attributes on model, which the service will respect?

If there is a way to inspect the parameters and enforce some validation rules, please provide an example.

**Comment by jahav** [comment]
Hi,

I have created a [gist](https://gist.github.com/jahav/48453c80e36e30a78d90eafb94308b42) demonstrating some possible way to use existing features of the SoapCore for validation.

Basically hook into an extension point and throw an Exception (preferably FaultException, where Detail has a DataContract).

Basically you will need to look into the `SoapCore.Extensibility` namespace.

Do note that the functionality is not very polished, e.g. `IModelBinder` interface has a setter on the interface, the type of `ModelTypes` property is `List<Type>`, instead of some read-only type/interface. Errors are rather cryptic (e.g. if you use ActionFilter without registering it in the DI, you get "Object Instance not set to an object" fault...).

**Comment by YaroslavKormushyn** [comment]
@jahav hi, thank you very much for the info and the example.
I successfully used the model binding validator and it works almost as expected.
I have one problem: when the client generates a FaultException, the Details are not serialized into the exception and there is no way to find out what validation errors occurred.

The error model is not present in the WSDL at all, which is why it's not present.
I tried running your gist, but the detail is not present.

Maybe I'm using it wrong, but a simple catch with `FaultException` does not show any Details.
Is that expected behavior?

**Comment by jahav** [comment]
/disclaimer: Not a developer of SoapCore and not an expert at SOAP. 

Hi @YaroslavKormushyn 
I only tried to run gist through SoapUi before submitting. The fault along with detail is being sent, but as you discovered the WSDL generated doesn't have a fault contract, so client doesn't know about detail. 

That should have been remedied by adding
`[FaultContract(typeof(SoapValidationResult))]` to the GreetMe operation (that should have created a contract in WSDL that can be imported by the client).

Except the WSDL is not generated correctly, not sure why (it references an element that is not present). So I can't import it as connected service in another project.

To answer your question: That (being unable to get fault details) is expected behavior when operation is missing faultcontract.  I forgot to add fault contract to the service in the gist and when I tried to add it, I found a bug I have no idea how to fix/work around

Basically the server sends this, but client doesn't understand it because WSDL is wrong.

```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Body>
		<s:Fault>
			<faultcode>s:Sender</faultcode>
			<faultstring>Validation failed.</faultstring>
			<detail>
				<ValidationResult xmlns="https://tempuri.org/SoapCoreValidation" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
					<Failures>
						<Failure>
							<ErrorMessage>'Given Name' must not be empty.</ErrorMessage>
							<PropertyName>GivenName</PropertyName>
							<Severity>Error</Severity>
						</Failure>
					</Failures>
				</ValidationResult>
			</detail>
		</s:Fault>
	</s:Body>
</s:Envelope>
 
```

**Comment by jahav** [comment]
@YaroslavKormushyn I looked through source code of SoapCore and found the issue. Be mindful to keep name of the class and name in the data contract same, at least someo or I make a PR.

Anyway, I have updated the gist and it should now work fine. Just run it, create a project (I used .NET Framework mstest), add connected service and try to run it against updated gist
```

using (var client = new GreeterServiceClient())
{
    try
    {
        var result = client.GreetMe(new User
        {
            GivenName = "Luccila"
        });
    }
    catch (FaultException<SoapValidationResult> ex)
    {
        var errorMessage = string.Join(", ", ex.Detail.Failures.Select(y => y.ErrorMessage));
        Console.WriteLine("Got {0}", errorMessage);
    }
}

```

**Comment by YaroslavKormushyn** [comment]
@jahav thank you for checking, that was the issue.
Sir, you helped me a lot! Thank you!

P.S.: For anyone reading this, be aware that the `Name` property in the `DataContract` attribute of the `SoapValidationResult` and `SoapValidationFailure` is mandatory (for now). Otherwise the results are not serialized and you end up with an empty `Detail` array in the exception.
