### ISSUE TITLE
Removal of xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"

### ISSUE THREAD

**Issue by Vikramadityagarg** [DigDes/SoapCore#470]
Hi ,

We have a requirement to import generated WSDL into Azure API Management Service. However API Manager Service does not support xs:import ( XSD Import). I want to remove the xsd import elements from WSDL and want to include the schema content itself into WSDL.

<xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
<xs:import namespace="http://schemas.datacontract.org/2004/07/System"/>

The above need to be removed. I am using SOAPCore 1.0.0 with netcoreapp3.1 . Please advise any pointers how this can be done. Does the framework supports this and if not what is the remedy for it.

Thanks
Vikram Garg

**Comment by andersjonsson** [comment]
The imports seem to be hardcoded
https://github.com/DigDes/SoapCore/blob/1160177e9d69021a27e606b2f1dbbee87dbcfd3b/src/SoapCore/Meta/MetaBodyWriter.cs#L297-L303

If you feel like doing a PR it should be possible to add an override to SoapCoreOptions.

The simplest solution would probably be to add a property `List<string> WsdlImports` (naming is hard 😆).
If that list is null then the defaults are added to the WSDL, otherwise the ones from the list are added.
