### ISSUE TITLE
Does AddSoapWsSecurityFilter only work for one set of credentials?

### ISSUE THREAD

**Issue by Drahkir** [DigDes/SoapCore#775]
I'm writing a SOAP based service with SoapCore and it needs to use WS-Security to authenticate the user.  It seems like AddSoapWsSecurityFilter gets initialized in StartUp with a single user.  

How would I make it so AddSoapWsSecurityFilter works for more than one user?  I plan on manually authenticating the credentials myself against our user database.  Is there a way to get the username/password token from AddSoapWsSecurityFilter ?

![image](https://user-images.githubusercontent.com/245618/145119138-d1866631-afa4-4ff1-aa70-4585499a81ea.png)

**Comment by andersjonsson** [comment]
That's just shorthand för `services.AddSoapMessageFilter(new WsMessageFilter(username, password))`
Take a look at the implementation for `WsMessageFilter` https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/WsMessageFilter.cs

Copy that implementation and check the credentials any way you like :)

If you want to return a custom message when the authentication fails, instead of throwing an exception, you can use `.AddSoapMessageProcessor()` instead of a message filter
