### ISSUE TITLE
XmlSerializer generated WSDL contains invalid enum references

### ISSUE THREAD

**Issue by yori-s** [DigDes/SoapCore#804]
Using the sample service: http://localhost:5050/Service.asmx?wsdl

1.1.0.22 generated the following:
```wsdl
<xsd:complexType name="ComplexModelResponse">
  <xsd:sequence>
    <!-- ... -->
    <xsd:element minOccurs="1" maxOccurs="1" name="TestEnum" type="tns:TestEnum" />
  </xsd:sequence>
</xsd:complexType>
<!-- ... -->
<xsd:simpleType name="TestEnum">
  <!-- ... -->
</xsd:simpleType>
```

Starting around 1.1.0.23 (6834c3f6a6aa36723f8ae646fb6ad1829b060542 as mentioned in #791), the namespace prefix is gone, making the wsdl invalid:
```wsdl
<xsd:complexType name="ComplexModelResponse">
  <xsd:sequence>
    <!-- ... -->
    <xsd:element minOccurs="1" maxOccurs="1" name="TestEnum" type=":TestEnum" />
  </xsd:sequence>
</xsd:complexType>
```

DataContractSerializer generated WSDL looks fine in this respect.

**Comment by yori-s** [comment]
It looks like a side effect of passing separate `XmlNamespaceManager`s to `MetaBodyWriter` and `MetaMessage` in #782:

https://github.com/DigDes/SoapCore/blob/f8842f1617dc0109e0338e40f4b312b6d0240862/src/SoapCore/SoapEndpointMiddleware.cs#L170-L179

Prior to the change, `MetaMessage` would register the `tns` prefix with the namespace manager shared with `MetaBodyWriter`, (presumably) before the latter looked it up.

https://github.com/DigDes/SoapCore/blob/f8842f1617dc0109e0338e40f4b312b6d0240862/src/SoapCore/Meta/MetaMessage.cs#L61
https://github.com/DigDes/SoapCore/blob/f8842f1617dc0109e0338e40f4b312b6d0240862/src/SoapCore/Meta/MetaBodyWriter.cs#L953-L962

I'd be happy to open a pr if someone will review it.

**Comment by andersjonsson** [comment]
Oh, I see! That's my bad.
That PR was to allow separate namespace overrides per messageEncoder, but since meta MetaBodyWriter doesn't use an encoder for it's own output it should not have those overrides.

If you add the tns-namespace in GetXmlNamespaceManager instead, it should be fine. Right after `.AddDefaultNamespaces()`.
Or am I missing something?

https://github.com/DigDes/SoapCore/blob/f8842f1617dc0109e0338e40f4b312b6d0240862/src/SoapCore/SoapEndpointMiddleware.cs#L814-L816
