### ISSUE TITLE
Complex model input from SoapUI is always null

### ISSUE THREAD

**Issue by Joostul** [DigDes/SoapCore#82]
I am trying to make a Soap service with SoapCore. I am using SoapUI to test this service. However I cannot get complex types to post any data. The properties always come in as null. Even when I use your sample application.

This is the request that SoapUI creates:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:PingComplexModel>
         
         <tem:inputModel>
            
            <tem:StringProperty>sdfwwef</tem:StringProperty>
            <tem:IntProperty>1</tem:IntProperty>
         </tem:inputModel>
      </tem:PingComplexModel>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by Fram90** [comment]
Same issue here. Complex object is populated with nulls.
@Joostul thanks for the idea with XmlSerializer, it solves the problem.

**Comment by Joostul** [comment]
@Fram90 Actually I've been working on my application and now it works again with DataContractSerializer. I believe it has to do with Kestrel vs HttpSys since I switched to HttpSys but can't be sure.

**Comment by neilsimp1** [comment]
I too had to switch to XmlSerializer.
Here's a related SO post: https://stackoverflow.com/questions/1651010/datacontractserializer-does-not-properly-deserialize-values-for-methods-in-obje
It could be related to alphabetical order or the `Order` attribute on your properties. XmlSerilizer, on the other hand, just worked.

**Comment by jszybisz** [comment]
I have resolved a problem by the following code modification

before:
 app.UseSoapEndpoint<EchoSoap>($"/Echo.asmx", new BasicHttpBinding());

after:
app.UseSoapEndpoint<EchoSoap>($"/Echo.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer);

**Comment by GO74** [comment]
I also encountert the 'null' problem. However, in my case XmlSerializer doesn't work, while DataContractSerializer doesn't.

`app.UseSoapEndpoint<MyService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer);`
... no luck

` app.UseSoapEndpoint<MyService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.DataContractSerializer);`
... works like expected

**Comment by matiasarri** [comment]
I have had tha same problem. Now, the XML it's mapping correctly. 
BUT when i create a Client to consume it, changes the contract reference.  

my method it's 
void SI_PO_004_SIP_In(ZALEAUD01 ZALEAUD01);
but, in place of that... implements:
Function SI_PO_004_SIP_In(ByVal request As ServiceReference1.SI_PO_004_SIP_InRequest) As ServiceReference1.SI_PO_004_SIP_InResponse

If i use:
app.UseSoapEndpoint<MyService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.DataContractSerializer);
XML not mapping, but in client implements correctly

if i use
app.UseSoapEndpoint<MyService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer)
maps it correctly but in client does it the same that i explained before
why that??

some one can help me?

**Comment by matiasarri** [comment]
I found the cause why  app.UseSoapEndpoint("/Service.asmx", new BasicHttpBinding(), SoapSerializer.DataContractSerializer); sets the propertys always null. because it's mapping the propertys in the strict order than you are defineds

for exapmle:

public class Add
        {
            public int X{ get; set; }
            public int Z{ get; set; }
        }

SOAP XML
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:alg="http://schemas.datacontract.org/2004/07/Algoritmo.SoftCereal.ApiSoftCereal.Soap.Services.Algoritmo.SoftCereal.ApiSoftCereal.Model">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:Add>
		<alg:X>1</alg:X>
        <alg:Z>2</alg:Z>
      </tem:Add>
   </soapenv:Body>
</soapenv:Envelope>

Work!

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:alg="http://schemas.datacontract.org/2004/07/Algoritmo.SoftCereal.ApiSoftCereal.Soap.Services.Algoritmo.SoftCereal.ApiSoftCereal.Model">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:Add>
        <alg:Z>2</alg:Z>
		<alg:X>1</alg:X>
      </tem:Add>
   </soapenv:Body>
</soapenv:Envelope>
DON'T WORK
