### ISSUE TITLE
Empty httpContext body in tuner after update. 

### ISSUE THREAD

**Issue by armat07** [DigDes/SoapCore#861]
After update package to 1.1.0.28 httpContext body is empty in tuner, therefore in previous version it works.

**Comment by andersjonsson** [comment]
That’s weird. What version did you use before?

**Comment by armat07** [comment]
> That’s weird. What version did you use before?
1.1.0.8

**Comment by andersjonsson** [comment]
If I'm correct that was an effect of removing the memory buffering of the body in https://github.com/DigDes/SoapCore/commit/eaeb5c72be3195431eb8a9efd7a4739083a77003
Since the body has already been read there's nothing left to read.

Depending on what you're trying to do it might be possible to accomplish some other way, like an ISoapMessageProcessor.

It should be possible to get this working again, but it's going to take some time before I can look into it.
If you want to take a crack at it and submit a PR you are more than welcome.

Hopefully we can find a way to get this working without necessarily enabling buffering across the board

**Comment by armat07** [comment]
Thank you for response. Now I don't have solution. I will try get through ISoapMessageProcessor. If I find solution, i'm ready share it.

**Comment by andersjonsson** [comment]
https://github.com/DigDes/SoapCore/issues/842
OP in that issue had the same issue as you and solved it with an ISoapMessageProcessor
