### ISSUE TITLE
How get body?

### ISSUE THREAD

**Issue by vadimpain** [DigDes/SoapCore#926]
I need to get the body or the entire xml of the request for subsequent sending and logging. I tried to get it in Tune, but the body came back empty due to deletion from memory. Tell me how can this be done?

**Comment by andersjonsson** [comment]
In #842 I showed a way to do it with an asp.net core middleware, before hitting SoapCore.

Otherwise I recommend taking a look at ISoapMessageProcessor (init with services.AddSoapMessageProcessor()).
That gives you the power to inspect the message, and change it if you need to, for both request and response.

You can take a look at #844 to see an example of how that works

**Comment by vadimpain** [comment]
@andersjonsson sorry for such a long answer. The option using AddSoapMessageProcessor () helped me solve my problem. Thanks
