### ISSUE TITLE
Middleware causes performance issues when trying to get TrailingServicePathTuner service

### ISSUE THREAD

**Issue by kemsky** [DigDes/SoapCore#942]
We are using LightInject as DI container (old project migrated to .NET Core).

`SoapEndpointMiddleware` attempts to get `TrailingServicePathTuner` on each HTTP call to server (it can be a call to a completely unrelated controller action) and it causes service delegate factory recompilation in LightInject because it attempts to resolve unregistered service.  Furthermore,  in our case explicit registration of `TrailingServicePathTuner` breaks everything, so we had to extend this class and override its method to make it do nothing. 

I think it makes sense to make `TrailingServicePathTuner` completely optional to allow fast path without any attempts to get service or provide some default registration to avoid such unexpected results.

There were attempts to do something with it like #856.

**Comment by andersjonsson** [comment]
That would be a problem, yes. I don't know why #856 was closed before we could merge it, but I'm not sure that it would have solved your problem, since it would need to get TrailingServicePathTuner as a fallback (to avoid breaking existing users).

I would be happy to review a PR if you have ideas.

It might be ok to only get the TrailingServicePathTuner in the constructor of SoapEndpointMiddleware and use that as a backup after attempting to get a ServicePathTuner by interface.
