### ISSUE TITLE
[Question] Is it possible to use this to re-implement a SOAP service on azure functions

### ISSUE THREAD

**Issue by MikeGHAtCOM** [DigDes/SoapCore#948]
Is it possible (and has anyone done it) to use this to re-implement a soap service on azure functions?

**Comment by andersjonsson** [comment]
Never worked with azure functions myself, but it will probably work. I've seen some examples of asp.net core applications being hosted within an azure function.
However I think it will be very inefficient since the startup time would be massive compared to the running time of a single operation.

If I had to do it I would probably rip out the parts of SoapCore that parses and serializes the request and response and just use that, with hardcoded types, in the Azure function. But as I said, I've never worked with Azure functions, so I'm just guessing 😅
