### ISSUE TITLE
How to add username and password verification

### ISSUE THREAD

**Issue by niuyacong** [DigDes/SoapCore#954]
We are expecting a reply

**Comment by UweKeim** [comment]
Here is one reply, hope it is what you expect.

My reply is:

The writing style of your issue here is very rude. Neither did you provide a thorough error or feature description, nor did you communicate politely. 

After all the authors are generously enough to provide a free library and free support, so the least I would expect is to show them respect for their hard work.

For what it is worth, I recommend reading "[How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)" over at Stack Overflow. 🚀
