### ISSUE TITLE
Help me please! How can i set the name of operation response?

### ISSUE THREAD

**Issue by xZ2020** [DigDes/SoapCore#957]
![image](https://github.com/DigDes/SoapCore/assets/69611749/5731f026-7a4e-4265-baf7-d72230911ee0)

**Comment by xZ2020** [comment]
In .net framework web service, it can be set by using attribute like this:
<img width="553" alt="a525a96647199ce04290959981a6f42" src="https://github.com/DigDes/SoapCore/assets/69611749/117223a4-7082-455e-93fe-e64a1558518f">

**Comment by andersjonsson** [comment]
Based on https://github.com/DigDes/SoapCore/blob/18d041a5f5b0c4ce933e45a0566e947c3d0aa4c8/src/SoapCore/Meta/MetaBodyWriter.cs#L363-L366 I think that you can use `[return:MessageParameter(Name = "return")]` on the method

Otherwise you might be able to create a class and return that instead of just the string. Should produce the same WSDL
```
public class downLoad2DBinResponse
{
    public string return;
}
```

**Comment by xZ2020** [comment]
Thanks！！
