### ISSUE TITLE
SoapCore tightly coupled to Microsoft.Extensions.DependencyInjection without support for other DI containers like SimpleInjector

### ISSUE THREAD

**Issue by OgonnaOG** [DigDes/SoapCore#978]
Noticed that SoapCore doesn't have support for dependency injector containers like SimpleInjector. 
Any possibility this can be looked into?

**Comment by andersjonsson** [comment]
I'm not quite sure how that would work, without introducing another abstraction layer for DI, but if you have an idea you are more than welcome to submit a PR. Preferably just an extensions point that can be used for other alternatives as well.

Most DI containers have opted to implement an integration package for microsoft DI abstractions that will work nicely but it seems that SimpleInjector have chosen a different path (https://docs.simpleinjector.org/en/latest/aspnetintegration.html)

If I were you I'd look into building an integration package directly for the microsoft DI abstractions, instead of attempting to shim something into SoapCore

**Comment by OgonnaOG** [comment]
Ok. 

Hangfire does something in that line I believe where its registered like this. 

```
services.AddHangfire(config =>
{    
    config.UseActivator(new SimpleInjectorJobActivator(container));
});
```

I'll look at their implementation and see if that can be ported over in similar fashion.
